name: Hprofile Actions 
on:
  push:
    branches:
      - main
  workflow_dispatch:

  pull_request:
    branches:
      - main
 
jobs:
  Testing-Code-Quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: cache Maven Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
            

      - name: Run Tests with Maven
        run: mvn  test
        timeout-minutes: 10

      - name: Checkstyle
        run: mvn checkstyle:checkstyle

      - name: Install Java 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup SonarQube     
        uses: warchant/setup-sonar-scanner@v7   

      - name: SonarQube Scan
        run: sonar-scanner
             -Dsonar.host.url=${{ secrets.SONACLOUD_URL }}
             -Dsonar.login=${{ secrets.SONACLOUD_TOKEN }}
             -Dsonar.organization=${{ secrets.SONACLOUD_ORG}}
             -Dsonar.projectKey=${{ secrets.SONACLOUD_PRJ }}
             -Dsonar.sources=src/
             -Dsonar.junit.reportPaths=target/surefire-reports
             -Dsonar.java.jacoco.reportPaths=target/jacoco.exec
             -Dsonar.java.checkstyle.reportPaths=target/site/checkstyle-result.xml
             -Dsonar.java.binaries=target/classes/com/visualpathit/account

            


       





  
        
